apiVersion: idx.inspur.com/v1alpha1
kind: FileSync
metadata:
  name: example-mini-reader
spec:
  global:
    mq: NATS
  nats:
    ip: "nats-edge.default.svc.cluster.local"
    port: 4222
  reader:
    nodeSelector:
      kubernetes.io/hostname: centos78-0
    image: "filereader:8.1.0-arm"
    srcPath: "/example-mini-reader/src"
    dataTopic: "examplesingle"     # streamName
    dataSliceSize: "1m"
    fmodeRead: 0
    userRead: 0
    logsyncMode: 0
