apiVersion: apps/v1
kind: Deployment
metadata:
  name: filesync-controller
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      name: filesync-controller
  template:
    metadata:
      labels:
        name: filesync-controller
    spec:
      serviceAccountName: filesync-controller
      containers:
      - name: fsc
        image: idx/filesync-controller:0.4.0
        imagePullPolicy: IfNotPresent