---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: filesync-controller
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: filesync-controller-cluster-role
  namespace: default
rules:
- apiGroups:
  - ''
  resources:
  - events
  verbs:
  - create
  - update
  - patch
- apiGroups:
  - idx.inspur.com
  resources:
  - filesyncs
  - filesyncs/status
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - ''
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ''
  resources:
  - configmaps
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - deployments/status
  verbs:
  - create
  - get
  - list
  - watch
  - patch
  - update
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: filesync-controller-cluster-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: filesync-controller
  namespace: default
roleRef:
  kind: ClusterRole
  name: filesync-controller-cluster-role
  apiGroup: rbac.authorization.k8s.io
